#include<stdio.h>
main()
{
   int h,v,a;
   clrscr();
   gotoxy(15,5);
   printf("************************************************\n");
   v=6;
   while(v<=20)
   {
       gotoxy(15,v);
       printf("*");
       gotoxy(62,v);
       printf("*");
       v++;
   }
   gotoxy(15,21);
   printf("************************************************");
}
